# Generated by Django 5.2.14 on 2026-06-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nlp_engine', '0001_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BentukTidakBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_tidak_baku', models.CharField(db_index=True, help_text='Bentuk penulisan yang tidak baku', max_length=100, unique=True)),
                ('kata_baku', models.CharField(help_text='Bentuk baku yang benar', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bentuk Tidak Baku',
                'verbose_name_plural': 'Bentuk Tidak Baku',
                'db_table': 'bentuk_tidak_baku',
                'ordering': ['kata_tidak_baku'],
            },
        ),
        migrations.CreateModel(
            name='FrasaKorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frasa', models.CharField(db_index=True, help_text='Pasangan 2 kata (bigram)', max_length=200, unique=True)),
                ('frekuensi', models.IntegerField(default=0, help_text='Jumlah kemunculan frasa di korpus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Frasa Korpus',
                'verbose_name_plural': 'Frasa Korpus',
                'db_table': 'korpus_frasa',
                'ordering': ['-frekuensi'],
            },
        ),
        migrations.CreateModel(
            name='KataKamus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata', models.CharField(db_index=True, help_text='Kata baku dari KBBI', max_length=100, unique=True)),
                ('kelas_kata', models.CharField(blank=True, help_text='Kelas kata (Nomina, Verba, Adjektiva, dll)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kata Kamus',
                'verbose_name_plural': 'Kata Kamus',
                'db_table': 'kamus_kata',
                'ordering': ['kata'],
            },
        ),
    ]
