# Generated by Django 5.2.14 on 2026-06-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_engine', '0003_gin_trgm_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AturanAwalKalimat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_terlarang', models.CharField(db_index=True, help_text='Kata yang dilarang di awal kalimat (misal: sehingga, dan)', max_length=50, unique=True)),
                ('saran_pengganti', models.CharField(help_text='Saran kata pengganti (misal: Akibatnya, Dengan demikian)', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aturan Awal Kalimat',
                'verbose_name_plural': 'Aturan Awal Kalimat',
                'db_table': 'aturan_awal_kalimat',
                'ordering': ['kata_terlarang'],
            },
        ),
    ]
