# Generated by Django 5.2.14 on 2026-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_engine', '0004_aturanawalkalimat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katakamus',
            name='kelas_kata',
            field=models.CharField(blank=True, help_text='Kelas kata (Nomina, Verba, Adjektiva, dll)', max_length=255, null=True),
        ),
    ]
